builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archive:
  format: binary
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
