// Code generated by mockery v1.0.0. DO NOT EDIT.

package stats

import mock "github.com/stretchr/testify/mock"
import vici "github.com/lunarway/strong-duckling/internal/vici"

// mockInfoReporter is an autogenerated mock type for the infoReporter type
type mockInfoReporter struct {
	mock.Mock
}

// Info provides a mock function with given fields: buildVersion, strongswan
func (_m *mockInfoReporter) Info(buildVersion string, strongswan vici.Version) {
	_m.Called(buildVersion, strongswan)
}
