// Code generated by mockery v1.0.0. DO NOT EDIT.

package strongswan

import mock "github.com/stretchr/testify/mock"

// MockIKESAStatusReceiver is an autogenerated mock type for the IKESAStatusReceiver type
type MockIKESAStatusReceiver struct {
	mock.Mock
}

// IKESAStatus provides a mock function with given fields: ikeSAStatus
func (_m *MockIKESAStatusReceiver) IKESAStatus(ikeSAStatus IKESAStatus) {
	_m.Called(ikeSAStatus)
}
