// Code generated by mockery v1.0.0. DO NOT EDIT.

package strongswan

import mock "github.com/stretchr/testify/mock"
import vici "github.com/lunarway/strong-duckling/internal/vici"

// MockReporter is an autogenerated mock type for the Reporter type
type MockReporter struct {
	mock.Mock
}

// IKESAStatus provides a mock function with given fields: conn, sa
func (_m *MockReporter) IKESAStatus(conn vici.IKEConf, sa *vici.IkeSa) {
	_m.Called(conn, sa)
}
